import OpenAI from "openai"

const openai = new OpenAI()

const SYSTEM_PROMPT = `You are a strictly neutral local government analyst. Your job is to summarize public policy updates in plain language for everyday residents.

Rules:
- Use an 8th grade reading level — short sentences, common words
- Never express a political opinion or editorial slant
- Describe facts only: what the policy does, not whether it is good or bad
- personal_impact must start with exactly "This could mean..."
- category must be exactly one of: housing, taxes, schools, roads, utilities, safety, other

Return only a JSON object with these three fields:
{
  "plain_summary": "<2 sentences describing what this update does>",
  "personal_impact": "<1 sentence starting with 'This could mean...' explaining the effect on a local resident>",
  "category": "<one of the seven categories above>"
}`

export interface BillContext {
  bill_number?: string | null
  sponsor?: string | null
  sponsor_party?: string | null
  sponsor_state?: string | null
  bill_status?: string | null
  vote_result?: string | null
  committee?: string | null
}

export interface SummarizeResult {
  plain_summary: string
  personal_impact: string
  category:
    | "housing"
    | "taxes"
    | "schools"
    | "roads"
    | "utilities"
    | "safety"
    | "other"
  // passthrough — stored as-is, not generated by the model
  bill_number: string | null
  sponsor: string | null
  sponsor_party: string | null
  sponsor_state: string | null
  bill_status: string | null
  vote_result: string | null
  committee: string | null
}

function buildContextLines(ctx: BillContext): string {
  const lines: string[] = []
  if (ctx.bill_number) lines.push(`Bill: ${ctx.bill_number}`)
  if (ctx.sponsor) {
    const party = ctx.sponsor_party ? ` [${ctx.sponsor_party}]` : ""
    const state = ctx.sponsor_state ? `-${ctx.sponsor_state}` : ""
    lines.push(`Sponsor: ${ctx.sponsor}${party}${state}`)
  }
  if (ctx.committee) lines.push(`Committee: ${ctx.committee}`)
  if (ctx.bill_status) lines.push(`Status: ${ctx.bill_status}`)
  if (ctx.vote_result) lines.push(`Vote: ${ctx.vote_result}`)
  return lines.length ? lines.join("\n") + "\n\n" : ""
}

export async function summarizeUpdate(
  title: string,
  rawText: string,
  location: string,
  context: BillContext = {},
): Promise<SummarizeResult | null> {
  try {
    const response = await openai.chat.completions.create({
      model: "gpt-4o-mini",
      response_format: { type: "json_object" },
      messages: [
        { role: "system", content: SYSTEM_PROMPT },
        {
          role: "user",
          content: `Location: ${location}\n\n${buildContextLines(context)}Title: ${title}\n\nContent:\n${rawText}`,
        },
      ],
    })

    const text = response.choices[0].message.content ?? ""
    const parsed = JSON.parse(text)

    return {
      plain_summary: parsed.plain_summary ?? "",
      personal_impact: parsed.personal_impact ?? "",
      category: parsed.category ?? "other",
      bill_number: context.bill_number ?? null,
      sponsor: context.sponsor ?? null,
      sponsor_party: context.sponsor_party ?? null,
      sponsor_state: context.sponsor_state ?? null,
      bill_status: context.bill_status ?? null,
      vote_result: context.vote_result ?? null,
      committee: context.committee ?? null,
    }
  } catch {
    return null
  }
}
